# -*- coding: utf-8 -*-

# Balance small amount
CCAT_BALANCE_SMALL_AMOUNT_BTC = 0.001
CCAT_BALANCE_SMALL_AMOUNT_USDT = 1

# Order status
CCAT_ORDER_STATUS_ORDERING = 'ordering'
CCAT_ORDER_STATUS_CANCELING = 'canceling'
CCAT_ORDER_STATUS_OPEN = 'open'
CCAT_ORDER_STATUS_PART_FILLED = 'part_filled'
CCAT_ORDER_STATUS_FILLED = 'filled'
CCAT_ORDER_STATUS_CANCELED = 'canceled'

# Order Type
CCAT_ORDER_TYPE_LIMIT = 'limit'
CCAT_ORDER_TYPE_MARKET = 'market'

# Order side
CCAT_ORDER_SIDE_BUY = 'bid'
CCAT_ORDER_SIDE_SELL = 'ask'

# Withdraw Status
CCAT_WITHDRAW_STATUS_UNKOWN = 'unknown'
CCAT_WITHDRAW_STATUS_QUEUED = 'queued'
CCAT_WITHDRAW_STATUS_HANDLED = 'handled'
CCAT_WITHDRAW_STATUS_CONFIRMING = 'confirming'
CCAT_WITHDRAW_STATUS_CONFIRMED = 'confirmed'
